### ISSUE TITLE
Login with oauth enabled

### ISSUE THREAD

**Issue by F0ob4r** [markdown-confluence/markdown-confluence#174]
Hi,
is there a way to use the plugin with 2FA enabled? In this case it would be OAUTH

I get the following error:

{
    "httpError": {
        "status": 401,
        "headers": {
            "content-type": "text/html;charset=utf-8",
            "content-length": "754",
            "connection": "keep-alive",
            "set-cookie": [
                "JSESSIONID=XXXX; Path=/; HttpOnly"
            ],
            "x-seraph-loginreason": "AUTHENTICATED_FAILED",
            "www-authenticate": "OAuth realm=\"https%3A%2F%2Fexample.com\"",
            "content-language": "de",
            "date": "Tue, 25 Apr 2023 07:14:30 GMT",
            "strict-transport-security": "max-age=31536000; includeSubDomains"
        }
    },
    "requestConfig": {
        "url": "/api/user/current",
        "method": "GET",
        "params": {}
    }
}

**Comment by andymac4182** [comment]
My understanding is this should work using an API token generated following https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

Is that the api token you used?

**Comment by F0ob4r** [comment]
Ahm no, the Confluence Instance is on premise. I created an user token.

**Comment by andymac4182** [comment]
Ahh currently the plug-in only supports cloud instances. It's on the list to support on premises instances. 

https://github.com/obsidian-confluence/obsidian-confluence/issues/91
