### ISSUE TITLE
mermaid.js rendering does not use theme styling

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#184]
I started using the mermaid js functionality in obsidian, which is supported by this plugin, and I noticed that the styling in the uploaded diagrams is different from what is rendered in obsidian.  perhaps this is expected behavior, since, of course confluence generally does not adopt the styling of your obsidian vault. 

However, I thought I'd raise it, because it's not too clear how, actually I would go about styling the uploaded diagrams, if I wanted them to be the same.

**Comment by andymac4182** [comment]
I haven't exposed it yet. 

Here is the current theme settings I am using.

https://github.com/obsidian-confluence/obsidian-confluence/blob/main/packages/mermaid-electron-renderer/src/index.ts#L25-L44

I was hoping to get some time to make a theme that looked native in Confluence. You can probably patch the rendered js files with what you want in there till I can expose this as a setting for you.

How would you like this exposed?

**Comment by jvsteiner** [comment]
Hmm.  I guess one approach could be to provide a dropdown in the global settings, where you could select from a few theme options.  Maybe:
1. Default (mostly B/W looking)
2. Confluence lookalike (I think this is what you have now)
3. Custom

The harder part is how to configure the custom option (3).  Some possibilities include:
a) A text entry box in global settings where users can paste the values like they appear in code:  You'd have to chose a format for the pasted values to be accepted, and parse it - maybe JSON, maybe comma separated...
b) Some css based solution, where a css file could be configured in settings:  looks cleaner, but no idea how to do it, since its consumed by the rendering copy of mermaid, not the one that is included in obsidian.
c) Use the frontmatter.  This stinks, because its a bunch of gaak on every page, and isn't reusable between documents
d) Pull each color setting out into a separate setting where you enter the color value: fills up too much space in settings :(

Probably (a) is the least undesirable, _but..._

Thinking about all this made me wonder:  Why is rendering mermaid even the responsibility of this plugin in the first place?  This plugin provides, essentially, export functionality to a specific document format - in this case ADF.  The exported document receives these diagrams as rendered png files.  Which is the same way it would receive other images I embed in the document.  Which already works fine, and I get WYSIWYG (more or less) in the confluence page.  

As an example, I also use an [html export plugin](https://github.com/KosmosisDire/obsidian-webpage-export)  where my mermaid diagrams end up, nicely rendered as pngs in the html output.  

Maybe this plugin doesn't need to do this task at all, and I could just control the styling of my mermaid diagrams using css within obsidian - something like:

```
.mermaid svg .node rect {
    fill: magenta !important;
    stroke: green !important;
}
```

and then let the rendering job be done by obsidian?

**Comment by andymac4182** [comment]
That HTML export plugin uses SVG which is what Obsidian renders mermaid to. I looked at doing the same but ran into https://jira.atlassian.com/browse/CONFCLOUD-1762.  I have to render the mermaid then screenshot it to have it as an image. 

You could embed the formatting in the diagram like this. I just tested and it works. https://dompl.medium.com/produce-great-looking-flowcharts-in-seconds-7f3bea64f2e2

<img width="738" alt="image" src="https://user-images.githubusercontent.com/1297073/234704593-c9bfd004-2835-4447-bded-d71ad9062cca.png">

**Comment by jvsteiner** [comment]
I tried this, and it does work.  I think it would be the only way to do multiple colors in the same diagram, like in the example you gave.  However, most of the time, I'm just looking to do monochrome rendering.  Maybe I'd invest in having a confluence matching theme, etc, but mostly plain old boring black and white is the goal ;)

**Comment by andymac4182** [comment]
Sounds good. Will have a look at making it simple to at least pick the different themes from Mermaid https://mermaid.js.org/config/theming.html#available-themes

**Comment by jvsteiner** [comment]
by the way, I tried the following syntax, and it seems to _kind of_ work:

```sample
%%{ init: { 'theme': 'base', 'themeVariables': { 'primaryColor': '#F0F0F0', 'primaryTextColor': '#000', 'primaryBorderColor': '#D3D3D3', 'lineColor': '#000', 'secondaryColor': '#fff', 'tertiaryColor': '#fff' } } }%%
flowchart TD
A[One thing] --> |Does something to| B[Another thing]
```

However, with the plugin, I couldn't get renders that respected the `primaryColor` - other colors were working fine, strangely.  I'll keep playing around.

**Comment by jvsteiner** [comment]
I still think it might be worth considering ways to eliminate the rendering functionality in this plugin.  I am seeing other strange aspects of how it works as well, for example:

<img width="125" alt="image" src="https://user-images.githubusercontent.com/1165328/234781837-c6d6239d-ccbe-441b-9cf4-40a74b8bdae6.png">

The arrow heads have different sizes when rendered by the plugin, however, not in obsidian.  The whole workflow makes it hard to know what you are going to get once you publish.  Life might be like a box of chocolates, but I guess it turns out I don't like my mermaid diagrams to be so...

**Comment by jvsteiner** [comment]
above might be related to: https://github.com/mermaid-js/mermaid/issues/4195

**Comment by andymac4182** [comment]
Ahh. Yeah I run a newer version of mermaid. I do my best to stay up to date. Once that fix it out I will release it.

**Comment by jvsteiner** [comment]
I really wonder if there is a way to convert re-render - as PNG - the obsidian compiled SVG output.  something like this maybe: https://stackoverflow.com/questions/3975499/convert-svg-to-image-jpeg-png-etc-in-the-browser

**Comment by andymac4182** [comment]
Yeah I actually take a screenshot of the svg from mermaid. I would probably just need to find the style sheets and any elements I need to wrap it in to make the css work. 

If you want to look you can see all the code for this in the electron package. Probably if I looked at the html export plugin it will show where the styles are copied from.

**Comment by andymac4182** [comment]
Fixed in https://github.com/markdown-confluence/markdown-confluence/pull/250
Will be released in V5
