### ISSUE TITLE
Internal links do not work

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#223]
In a large document, if I make an internal link from one part of it to another using the standard Obsidian syntax, for example:

 `[[note-name#My Heading|visible link text]]`  (let's say the actual configured title, using `connie-title` is "My Title")

when I publish the page, the link does not work.  The rendered link turns out as 

`.../pages/6767676767#My%20Heading`

where "6767676767" is the page ID, instead of:

`.../pages/6767676767/My+Title#My-Heading`

Not use of `+` and `-` instead of spaces, and the inclusion of the Title (although if you omit the title, it redirects and still works, although I'm not sure I would rely on this behavior)

**Comment by andymac4182** [comment]
Ahh thanks. I missed this in testing. Will fix that up for the next version 😀 

You can rely on that redirect behaviour. The only parts that 100% affect the page load is the site domain and the page id. Everything else is checked and redirected if wrong :)

**Comment by andymac4182** [comment]
Also need to fix this https://github.com/markdown-confluence/markdown-confluence/issues/226 which is in a different place
