### ISSUE TITLE
Feature Request - links to published pages in status modal

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#224]
As a user who just published a page, I would like to be able to click on a link, and go right to that published page and double check whether it rendered correctly, and possible to share it with others on my team from within confluence.  If, in the screenshot below, the text "test-file.md"  were a live link I could click on, with the actual confluence page link behind it, it would be super useful.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/1165328/235067928-7775408d-1ed6-4cbf-8a4d-0ee42fa36f68.png">

**Comment by andymac4182** [comment]
Great idea 😀 I have all the information for that so will have a look at adding that.
