### ISSUE TITLE
Links in the status modal dont work

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#230]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1165328/235283663-a02cde86-2ec4-4533-9dde-54e69caaf582.png">

In the above, the underlying link has two slashes after the domain which make them dysfunctional, like

`https://my.domain.net//wiki/spaces/NC/pages/6767676767/`

**Comment by andymac4182** [comment]
Does your site domain in settings have a slash at the end?

**Comment by jvsteiner** [comment]
yes it does

**Comment by jvsteiner** [comment]
I can confirm this is the cause: the link works if I remove the slash from settings, but I guess I'll probably not be the only person who puts one there.  might want to optionally strip it

**Comment by andymac4182** [comment]
Yeah I had in the back of my head to put some validation and handling on there. I want to rebuild the settings tab to be a bit more user friendly and also help with expanding to support https://github.com/markdown-confluence/markdown-confluence/issues/184 options.

**Comment by andymac4182** [comment]
Would links to all pages published even if they haven't changed be helpful?

**Comment by jvsteiner** [comment]
doubt it

**Comment by andymac4182** [comment]
Replacing this with https://github.com/markdown-confluence/markdown-confluence/issues/235
