### ISSUE TITLE
Internal link formatting has a few problems

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#231]
So I tried out the new feature of supporting links internally within a document and it doesn't work properly in my case.  I noticed the following:

for a link that started out life as:

`[[note-filename#Target Header|Visible link Text]]` - in obsidian

I ended up with a rendered link, in confluence that looks like this:

`https://my.domain.net//wiki/spaces/NC/pages/6767676767#Target%20Header`

1. There are two slashes after the domain, and before `wiki` in the path
2. There is not any slash after the pageid, and before the fragment (`#`)
3. The space is rendered still as `%20`  and not converted to a `-` as per confluence norms

When I fixed these manually the link worked, but not before

**Comment by andymac4182** [comment]
Thanks. I'll have another look. I should of known better than trying to just push a quick fix without testing it.

**Comment by jvsteiner** [comment]
1. above might be related to https://github.com/markdown-confluence/markdown-confluence/issues/230

**Comment by andymac4182** [comment]
Next attempt. This time I didn't rush and look at the wrong place https://github.com/markdown-confluence/markdown-confluence/commit/ed446e87a1a12d7014efeff37ae39e161b558e0c

**Comment by andymac4182** [comment]
Will leave the settings issue with the domain to the other issue. Fixed up the # links.
