### ISSUE TITLE
Changing title does not seem to work

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#238]
If I use the frontmatter setting `connie-title`, and I change the title set there, but do _not change_ any other content in the document, the title will not be changed - the plugin does not recognize title changes, using this setting, as an actual change to allow the possibility to update.

This is a very minor issue...

**Comment by andymac4182** [comment]
I just found this myself. My check to prevent republishing when no content change is too aggressive and isn't checking other things that might change like page title. I plan on fixing this soon.
