### ISSUE TITLE
Internal link formatting still has some issues

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#261]
Looks like there are still som issues here.  I created a link that looks like:

```
[[#High Level Scope|High Level Scope]]
```

and it's gets published as:

`.../pages/6767676767/The+title#High-Level%20Scope`

So the first space character is correctly translated to a `-`  but not the second (or other ones).

**Comment by andymac4182** [comment]
Yep :( Turns out I am not super smart and didn't do a global replace. Will fix when I am a little more awake sorry. 

Will be adding a way for people to add tests easily soon to help with this.

**Comment by andymac4182** [comment]
Should be fixed by https://github.com/markdown-confluence/markdown-confluence/commit/c01ae974445da898d69506fe754592d500b196f8
