### ISSUE TITLE
Error handling when a page is deleted

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#263]
In the case where a page on confluence gets deleted, but the corresponding note still exists in the obsidian vault, a 404 error results, with no further indication of what to do.  This could be a problem, if a team mate deletes a page, because you wouldn't necessarily know which page was deleted in order to delete it from your own vault.  More importantly, you might not _want_ to delete the content from your vault, just because someone else removed it from the confluence instance. 

recommend introducing an additional frontmatter tag, let's say: `connie-removed-upstream`.  This tag could be added automatically to a note, when a 404 error results.

when present, it means it the note will be skipped during the publishing process.

**Comment by andymac4182** [comment]
It can get set to Connie-publish: false which will exclude it from being picked up for publishing. 

Will add to the list of things for  next version.

**Comment by jvsteiner** [comment]
might want to remove the `connie-page-id` tag as well

**Comment by cwmccann** [comment]
I think I'm getting this error as well.  I was testing the workflow and deleted some pages from confluence.  Now I can't upload them again.  Is there a way to manually recover from this? 

Here's what the client is outputting:
```
❯ npx @markdown-confluence/cli
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 404".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.16.0
```

**Comment by jvsteiner** [comment]
If you deleted them on confluence, and you want to upload them back there, you can try deleting the `connie-page-id` tag and re-publishing it.

**Comment by cwmccann** [comment]
I purged the files from the trash, will this remove the tags?  I couldn't find any reference to tags in the confluence documentation.  Sorry, I'm not super familiar with how confluence works and much prefer Markdown, hence why I want to use this tool.

**Comment by cwmccann** [comment]
Never mind, I found it as front matter on the markdown file.  I never thought to look there.

**Comment by andymac4182** [comment]
@cwmccann All working okay now? 

Need to update the CLI results to be better at letting you know what has happened. 

Started a discussion if you could put some thoughts down would be appreciated https://github.com/orgs/markdown-confluence/discussions/267

Also have a discussion related to improvements for documentation https://github.com/orgs/markdown-confluence/discussions/268

**Comment by cwmccann** [comment]
Yeah, it's working now!  Thanks.

**Comment by andymac4182** [comment]
@jvsteiner Can you test this out with the latest in main? https://github.com/markdown-confluence/markdown-confluence/commit/33dde014ccc24368f065eec0a92dba3755644fc8 should handle this. I need to do some more testing myself but so far tested in CLI and Obsidian seems to be good :) 

Sorry it took a little bit to get to this.

**Comment by jvsteiner** [comment]
LGTM

**Comment by andymac4182** [comment]
Awesome :) will close this off and release
