### ISSUE TITLE
Getting 401 on confluence publish

### ISSUE THREAD

**Issue by justutkarsh** [markdown-confluence/markdown-confluence#266]
https://confluence.corp.mycompany.com
parent page id provided
Personal Access Token provided

**Comment by andymac4182** [comment]
Is this a cloud or on premise instance?
Guessing based on the domain its an on premise instance. Currently the core library don't have support for these instances. I hope to have a look at this soon. https://github.com/markdown-confluence/markdown-confluence/issues/91

**Comment by Emzetto** [comment]
Same with me. Confluence ist installed on premise (by the providing company). Feature would be excellent!

**Comment by andymac4182** [comment]
Closing off in favour of #91 . I did an evaluation today with the results on https://github.com/markdown-confluence/markdown-confluence/issues/91#issuecomment-1537293277
