### ISSUE TITLE
Mermaid is not working via the cli

### ISSUE THREAD

**Issue by cwmccann** [markdown-confluence/markdown-confluence#270]
Any Markdown document that has a mermaid diagram in it isn't being updated.

If the document is new, the contents of the document in confluence is "Page not published yet".
If the document is existing, and I add a mermaid diagram to it, nothing happens.

I'm not using obsidian, just a plain markdown files and syncing using the client.

Here's an example diagram:
```mermaid
graph LR
pub1[Publisher] -- publishes message --> MB[Message Broker]
MB -- receive message --> sub1[Subscriber 1]
MB -- receive message --> sub2[Subscriber 2]
```

I'm also noticed that images are not being synced.  I can open another ticket but thought that they might be related.

**Comment by andymac4182** [comment]
Sorry about this. I will look into this in the next 24 hours. 

Just confirming are you running the cli direct from npm or one of the wrapped versions Docker or GitHub Action?

Curious are you using a different editor that you would like the tooling installed into as a plugin or does the CLI work best for you?

**Comment by cwmccann** [comment]
Thanks for looking into it!

I'm running it using the npx client.  I'm using node version v18.16.0 which I think is the version the docker container uses.

As for tooling, I'm trying to come up with a workflow for writing software architecture documents and having them published on my companies confluence page.  I'd prefer to have all the artifacts in text and stored in git.  I've been playing around with [Structurizr](https://structurizr.com/) along with [arc42](https://arc42.org/) templates.  I'm still working out the kinks.

I'm using vscode as the editor, and will likely use gradle to combine the steps together.

Does that help?

**Comment by andymac4182** [comment]
I think I found the issue but the GitHub outage prevented me from finalising and testing the fix. 👎 

That is awesome. I would love to hear more about how you are integrating Structurizr with the workflow as I am a big fan and currently looking at options to integrate a similar workflow with [Compass](https://www.atlassian.com/software/compass) and Confluence to create a good overview of the systems that all connect together. I am looking at putting a bunch of examples together and your workflow is one of the main workflows I am looking at demoing. 

That helps a lot 👍

**Comment by andymac4182** [comment]
I have found the issue. The issue is that puppeteer only installs the browser when the package is installed :( I have fixed for the docker container.

I have to come up with a solution to install it if it isn't there.


Workaround:
If you run the below script in a random folder it will bootstrap the browser binaries. 

```bash
npm i puppeteer
```

**Comment by andymac4182** [comment]
I have a fix in 5.2.4 should mean it will "just work" the first time you publish after that version it will get the right browser for puppeteer. It will mean the first publish is a little slow.

**Comment by cwmccann** [comment]
It's working now.  The first time it didn't work for some reason, but the second time it did.  I think it's a puppeteer thing.

```
Downloading chrome r113.0.5672.63 - 128.1 MB [====================] 100% 0.0s 
ERROR: Failed to set up Chrome r113.0.5672.63! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: ENOENT: no such file or directory, open '/Users/chris/.cache/puppeteer/chrome/chrome-mac-x64.zip'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/chris/.cache/puppeteer/chrome/chrome-mac-x64.zip'
}
❯ ls /Users/chris/.cache/puppeteer/chrome/chrome-mac-x64.zip
ls: /Users/chris/.cache/puppeteer/chrome/chrome-mac-x64.zip: No such file or directory
❯ ls /Users/chris/.cache/puppeteer/chrome/
mac-113.0.5672.63
❯ npx @markdown-confluence/cli@5.2.4
Chrome (113.0.5672.63) downloaded to /Users/chris/.cache/puppeteer/chrome/mac-113.0.5672.63
Chrome (113.0.5672.63) downloaded to /Users/chris/.cache/puppeteer/chrome/mac-113.0.5672.63
Chrome (113.0.5672.63) downloaded to /Users/chris/.cache/puppeteer/chrome/mac-113.0.5672.63
Chrome (113.0.5672.63) downloaded to /Users/chris/.cache/puppeteer/chrome/mac-113.0.5672.63
Chrome (113.0.5672.63) downloaded to /Users/chris/.cache/puppeteer/chrome/mac-113.0.5672.63
... snip document diffs and cli output
```

**Comment by andymac4182** [comment]
Ahh I can see what is wrong. I am doing this multiple times at once due to multiple pages having mermaid on them. I need to make sure it just happens one time. Will look at that soon to fix up.

**Comment by cwmccann** [comment]
Images don't seem to be uploading either.  I can open a new issue if you like.

Looking at the output of the cli it's saying that it's all synced, but confluence is saying the image is unavailable.

Maybe I should start digging into the code instead of just asking you :)

**Comment by andymac4182** [comment]
Which image syntax are you using? `![[image.png]]` or `![](../images/image.png)` ? 

No issue asking questions here :) I am sure I have a few bugs still to be worked out. I will do my best to answer questions and fix things ASAP :)

**Comment by cwmccann** [comment]
I'm using `![Existing Deployment](images/existing.png)`

**Comment by andymac4182** [comment]
Ahh I have been using the wikilinks style. Will test and fix the other one. Sorry for the inconvenience.

Logged an issue to fix this https://github.com/markdown-confluence/markdown-confluence/issues/293

**Comment by andymac4182** [comment]
Fix incoming :) https://github.com/markdown-confluence/markdown-confluence/commit/9ee3c8c37024a8dc1db3ac66ebb12aba9cb58140

Will need some testing if you can. I have done some basic testing.

**Comment by andymac4182** [comment]
Fix should be in the latest version.

**Comment by cwmccann** [comment]
With @markdown-confluence/cli@5.2.6 I'm getting an invalid image path.

I wonder if it's because the image path is nested.

Here's my directory structure:

```
> tree
.
└── Architecture
    ├── 01 Introduction and Goals.md
    ├── 02 Architecture Constraints.md
    ├── 03 System Scope And Context.md
    └── In Progress
        ├── images
        │   └── sample.png
        └── test.md
```

And the contents of test.md
```
---
connie-publish: true
connie-page-id: '2713452561'
---
# Test page 

![Test Image](images/sample.png)
```

Here's what the diff states when running the client.
```
TESTING DIFF - Architecture/In Progress/test.md
{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"text":"Test page","type":"text"}]},{"type":"paragraph","content":[{"text":"Invalid Image Path","type":"text"}]}],"version":1}
{"version":1,"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Test page"}]},{"type":"paragraph","content":[{"type":"text","text":"Invalid Image Path"}]}]}
```

**Comment by andymac4182** [comment]
Ahh that makes sense. My readbinary function in file system  class doesn't do a relative read if possible. Will update that today. 

Sorry will try to get some easy to contribute to unit tests so you can provide and example for me to use in tests so I don't miss this.

**Comment by andymac4182** [comment]
Tested out the same pathing locally and I believe I have this finally fixed :( So sorry it took a few goes https://github.com/markdown-confluence/markdown-confluence/releases/tag/obsidian-confluence-root-v5.3.0

There is also updated documentation to match https://markdown-confluence.com/features/image-upload.html Please check if if you get a sec :)

**Comment by cwmccann** [comment]
It works!!

Thank you very much.

**Comment by andymac4182** [comment]
Awesome. Thanks for your patience as I worked it out.
