### ISSUE TITLE
Obsidian Plugin fails to load if a CSS snippet is deleted but not removed from Obsidian's `embeddedCssSnippets` array in `appearance.json`

### ISSUE THREAD

**Issue by dljsjr** [markdown-confluence/markdown-confluence#291]
I found that the plugin was crashing trying to load a file called `fullwidth-breakout.css` that I couldn't find anywhere in my vault, nor could I find a string reference to it in the JS bundle for the plugin.

It turned out that `fullwidth-breakout` was an entry in Obsidian's `appearance.json`'s `enabledCssSnippets` array; I think this was a custom snippet I had used at one point, but then I deleted the file from my snippets directory. Apparently Obsidian leaves the entry in the array (I guess in case the file shows back up in the future).

Honestly not even sure why the plugin needs to read all of my CSS snippets (I'm assuming for the mermaid theme matching functionality), but regardless, it was causing a crash 😅

**Comment by andymac4182** [comment]
Yep its for mermaid matching. I will fix that 👍 I thought Obsidian would of been a little smarter than that. Will get the fix out today for that.

**Comment by andymac4182** [comment]
Fix should be out soon https://github.com/markdown-confluence/markdown-confluence/commit/c825559c4c318d665996d4da0b2488666c44fcaa :)

**Comment by andymac4182** [comment]
Fix should be out in v5.2.5 https://github.com/markdown-confluence/markdown-confluence/pull/292

If you could confirm that would be amazing :)

**Comment by dljsjr** [comment]
I can confirm that the issue is fixed after updating via BRAT :)
