### ISSUE TITLE
Feature Request: Code block/fence for "raw" storage format XHTML

### ISSUE THREAD

**Issue by dljsjr** [markdown-confluence/markdown-confluence#296]
I saw the tracking issues for things like macros and ADF templates; I was wondering if it would be a useful feature as a stop-gap to have a code block fence `(```connie-raw` or something?) that allows a user to write XHTML fragments for storage representation directly in the .md.

I was playing around with appending macros (e.g. the Jira macro with a JQL query) and it appeared that it was getting stripped out wholesale when it was in the markdown text but the append command was valid when I send the XHTML up via `curl`. So it definitely seems *feasible*, but I don't know enough about the internals of md-confluence to know if this is a totally off-sides stop-gap :)

**Comment by andymac4182** [comment]
The plug-in doesn't use storage format for communication with Confluence. There is a codeblock for adf that takes json and will add that block in as you have described. You will just need to do as adf instead of storage format. 

Here is an example of a URL ( you can use to get `atlaskit_doc_format` normally known as [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/)

https://markdown-confluence.atlassian.net/wiki/rest/api/content/2916353?expand=body.atlas_doc_format,body.storage

Below example renders to a Decisions List
~~~md
```adf
{"type":"decisionList","attrs":{"localId":"39becc7a-48c3-4e2d-a6bc-35648d6689a2"},"content":[{"type":"decisionItem","attrs":{"state":"DECIDED","localId":"95268b83-2fc0-4801-9b4f-e5c42cc530e6"},"content":[{"text":"Decision to track","type":"text"}]},{"type":"decisionItem","attrs":{"state":"DECIDED","localId":"564ab974-e6fe-48d2-a144-507f5ec30906"},"content":[{"text":"Testing Decision 2","type":"text"}]}]}

```
~~~

The code that does this work is https://github.com/markdown-confluence/markdown-confluence/blob/main/packages/lib/src/MdToADF.ts#L114-L129

**Comment by dljsjr** [comment]
Whoooaaaaa, righteous. I'll try that out and see how far it gets me. Thanks!

**Comment by dljsjr** [comment]
I'm gonna abuse having the ear of a principal to ask this next question: What's the deal with the UUID in `localId` and how do I know what to assign there? Can I just generate a uuidv4?

~~I was able to at least validate that this works by pulling the ADF for a macro out of an existing page that I'm now mirroring so that's awesome. But if I want to inject macros in the future I'm not sure exactly what `localId` is.~~

I guess it's irrelevant, I was able to upload some `adf` without setting that attribute and it worked. This is incredible. Thank you for this plugin @andymac4182!!!!!

**Comment by andymac4182** [comment]
Honestly I don't work anywhere near the teams that work on that. I don't know anymore about the internals than you.

Glad you like the plug-in.

**Comment by andymac4182** [comment]
Be great to get some feedback in https://github.com/orgs/markdown-confluence/discussions/297 about the macros (with ADF if possible) for what macros should be simple / built in to work with and what the parameters should be.

**Comment by andymac4182** [comment]
Added some docs. Would appreciate a review (All the same content just published too the different places I store docs) 

HTML: https://markdown-confluence.com/features/raw-adf.html
Confluence: https://markdown-confluence.atlassian.net/wiki/spaces/docs/pages/3735553/Markdown-Confluence+Unleashing+the+Ninja+Power+of+Raw+Atlassian+Document+Format+Blocks
Original: https://github.com/markdown-confluence/docs-markdown-confluence/blob/main/src/features/raw-adf.md

**Comment by dljsjr** [comment]
> Added some docs. Would appreciate a review (All the same content just published too the different places I store docs)
> 
> HTML: [markdown-confluence.com/features/raw-adf.html](https://markdown-confluence.com/features/raw-adf.html) Confluence: [markdown-confluence.atlassian.net/wiki/spaces/docs/pages/3735553/Markdown-Confluence+Unleashing+the+Ninja+Power+of+Raw+Atlassian+Document+Format+Blocks](https://markdown-confluence.atlassian.net/wiki/spaces/docs/pages/3735553/Markdown-Confluence+Unleashing+the+Ninja+Power+of+Raw+Atlassian+Document+Format+Blocks) Original: [markdown-confluence/docs-markdown-confluence@`main`/src/features/raw-adf.md](https://github.com/markdown-confluence/docs-markdown-confluence/blob/main/src/features/raw-adf.md?rgh-link-date=2023-05-11T22%3A19%3A08Z)

Looks good, basically how I approached using the `adf` fence in my notes after you told me about it; the `atlas_doc_format` query param was documented on the v2 REST API for getting a page by ID so maybe it's not *that* mysterious 😅
