### ISSUE TITLE
This is not in the community plugins list

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#30]
I also tried to install manually, and even after fixing a bug, and building it, and moving the files to what I thought would be the correct place, I wasn't able to get it working.  This would be a really nice capability: any chance you are actually going to make it available in the community plugins marketplace?

If you are having trouble doing it, I suggest starting with the https://github.com/obsidianmd/obsidian-sample-plugin template

**Comment by jvsteiner** [comment]
actually I did manage to install it manually - I hope you publish this

**Comment by ugolafosse** [comment]
True, not in the plugins list, no access possible

**Comment by jvsteiner** [comment]
https://github.com/obsidianmd/obsidian-releases

I managed to publish one - the instructions are here.  The process wasn't too hard, or is there another reason why you can't.  Licensing maybe?

**Comment by ugolafosse** [comment]
> https://github.com/obsidianmd/obsidian-releases
> 
> I managed to publish one - the instructions are here. The process wasn't too hard, or is there another reason why you can't. Licensing maybe?

Thanks will do that !

**Comment by andymac4182** [comment]
I plan on adding it to the community plugins when I have finished off the UX a bit. I am iterating quickly adding a bunch of features I really want to support before publishing and also cleaning up the code / CI processes.  

Curious how did you hear about the plugin?

eg: https://github.com/obsidian-confluence/obsidian-confluence/pull/29
https://github.com/obsidian-confluence/obsidian-confluence/pull/26
https://github.com/obsidian-confluence/obsidian-confluence/pull/32

**Comment by jvsteiner** [comment]
> Curious how did you hear about the plugin?

google search works!  I was thinking of making such a thing myself.  I made a community plugin myself a month or so ago - called `s3-image-uploader` and got interested in other integrations that seemed to be missing.  As a product manager who spends a lot of time on confluence, but prefers editing in Obsidian, this seemed like an obvious integration that was suspiciously missing, so I poked around a bit.  if you need help on anything, or with testing, let me know.

**Comment by andymac4182** [comment]
Thanks @jvsteiner I am on Paternity Leave at the moment so trying to knock this off my list before I go back to work start of May. Over the next few weeks I plan on knocking off a few more features. Will get CI working tonight (I am in Brisbane, Australia) so you can use BRAT https://github.com/TfTHacker/obsidian42-brat to install the plugin and keep it updated. 

Be aware there isn't tests yet and also 1 path is hard coded to my machine while I get a fix working. 

Please leave Feature Requests as issues or discussions so I can see what I can get knocked out as quickly as I can to help others. Some things are a lot harder such as syncing back from Confluence to Obsidian due to there being a lot richer features in Confluence but will see what I can do.

**Comment by andymac4182** [comment]
I have BRAT working I am 99% sure. https://github.com/TfTHacker/obsidian42-brat/tree/main I will be testing this more next week due to family commitments over the next few days. 

Be great to see if that works nicely for a demo repo.

**Comment by ugolafosse** [comment]
<img width="802" alt="CleanShot 2023-04-07 at 00 49 34@2x" src="https://user-images.githubusercontent.com/44898829/230507819-6765ccf3-70af-476c-aa4c-f12ec697dfb9.png">
No ability to save my config settings, I always come back to an empty slate in setttings

**Comment by andymac4182** [comment]
Thanks. I'll see why that didn't work. I haven't had a chance to test the brat install but it was working locally.

**Comment by andymac4182** [comment]
Fix in v1.2.4 https://github.com/obsidian-confluence/obsidian-confluence/releases/tag/1.2.4

**Comment by andymac4182** [comment]
Submitted https://github.com/obsidianmd/obsidian-releases/pull/1867

**Comment by andymac4182** [comment]
Closing off as submitted to Obsidian releases :)
