### ISSUE TITLE
Usage-Obsidian page is empty 

### ISSUE THREAD

**Issue by rs16w** [markdown-confluence/markdown-confluence#309]
Hello, i would try your plugin, but i don't know, how?
doc's page is empty: https://markdown-confluence.com/usage/obsidian.html
pls could you fix it?

**Comment by andymac4182** [comment]
Sorry will update that page. The docs for the obsidian plugin are also at https://obsidian-confluence.com/

**Comment by rs16w** [comment]
> Sorry will update that page. The docs for the obsidian plugin are also at https://obsidian-confluence.com/

Am i right that this plugin allows me ONLY publishing content?
>allows you to publish markdown content from Obsidian to [Atlassian Confluence](https://www.atlassian.com/software/confluence)

What if i want just reformat content from MD to Atlassian conf?

something like this plugin obsidian://show-plugin?id=obsidian-md-to-jira

but as i know Jira markup != Confluence markup. And it's real problem %(

**Comment by andymac4182** [comment]
It currently is designed to publish.

What is the use case you are looking for?

**Comment by rs16w** [comment]
i'm using obsidian as draft for some articles that will migrate to confluence. But i have no possibility to configure this plugin to  work witk confluence. I just want select all content from obsidian-note, to push the button and have wiki formated content in my clipboard. Is it possible?

**Comment by andymac4182** [comment]
I don't use confluence wiki format in the plugin so at this point that isn't possible. 

Why can't you publish from obsidian? Is this because you are using on premise? Or is it you can't generate an api token?

**Comment by rs16w** [comment]
my company doesn't allows generate some tokens and different external access. And so i just can do it with old copy-paste:)

**Comment by andymac4182** [comment]
Because you can't copy paste ADF to Confluence the best I can think of is if I let you paste in a Session token or similar that would let you emulate a browser but is not great for security and also would only work for Cloud not Server / On Premise instances.
