### ISSUE TITLE
Wikilinks failing to be created

### ISSUE THREAD

**Issue by piotryordanov** [markdown-confluence/markdown-confluence#310]
So, in my markdown I have 

```
[[Power of Attorney]]
[[Power of Attorney#Conclusion]]
```

But, it gets rendered as 

```
https://alphacreat.atlassian.net//wiki/spaces/FINANCE/pages/65575
https://alphacreat.atlassian.net//wiki/spaces/FINANCE/pages/65575#Conclusion
```

Is this related to the latest updates?

**Comment by andymac4182** [comment]
Ahh :( Sorry a bug I need to fix. You have an extra `/` on the end of your confluence site domain. If you remove that it will all start working. 

I thought I fixed that sorry.

Making a note for myself to fix this in `SettingsLoader validateSettings` to parse the URL and build the setting from the parsed URL.

**Comment by piotryordanov** [comment]
Removing the `/` does fix it.
Thank you for the fast response!

**Comment by andymac4182** [comment]
No worries. 

Hope that is the only issue :)

**Comment by piotryordanov** [comment]
Yup it is :)

Unrelated question. Is it possible to prevent the folder `Confluence Page` to be published as a page?

**Comment by piotryordanov** [comment]
Nevermind, i was using folder notes wrongly!
