### ISSUE TITLE
Error while trying to build @markdown-confluence/lib package on react.

### ISSUE THREAD

**Issue by umschaudhary** [markdown-confluence/markdown-confluence#311]
Hi there, 

I am trying to install and use the @markdown-confluence/lib in one of our react app. However I am getting some issues while trying to build the project. Here I have attached the error screenshot. 

![Screenshot 2023-05-22 at 2 26 51 PM](https://github.com/markdown-confluence/markdown-confluence/assets/31402318/4caf49b6-ee0d-4ea6-9345-a71e48454a2b)

**Comment by andymac4182** [comment]
Curious what are you trying to do? It looks like you are using the filesystem loader which is designed for nodejs.

**Comment by umschaudhary** [comment]
> Curious what are you trying to do? It looks like you are using the filesystem loader which is designed for nodejs.

I am trying to implement this package to convert markdown to ADF with react. 
Is it not compatible with react? Or is it just for backend framework such as node.js?

**Comment by andymac4182** [comment]
The publisher class you are using is designed to publish pages to confluence. If you want to do that in the browser you will require a server to avoid cors issues and to write your own adaptor for loading the files. I did this for obsidian which doesn't use nodejs and runs in electron. 

I will write up an example of using the library to convert markdown to adf. There is a class called MdToAdf which is what you can use to convert between a markdown file and and adffile which has a property with the adf contents on it.

**Comment by umschaudhary** [comment]
@andymac4182 Thank you @andymac4182  for your prompt suggestion. I was able to fix the issue I was facing!

**Comment by andymac4182** [comment]
Awesome. Will this be released or is it an internal tool?

**Comment by umschaudhary** [comment]
> Awesome. Will this be released or is it an internal tool?

This will be released on Atlassian Marketplace :)

**Comment by andymac4182** [comment]
Please share a link when it's ready :) keen to see how the library is used. 

Feel free to join discord. Happy to help if there is other parts of the library I need to open up for use to improve the experience.
