### ISSUE TITLE
Ability to specify Confluence Page ID in YAML Frontmatter

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#33]
Individual pages sync:

I often contribute to difference confluence spaces, and even from within the same space, I do not want to maintain my folder structure in Obsidian in the same structure as it is in Confluence.  This point is more important when I need to restructure the pages in confluence - it means I will need to do the same, separately, in Obsidian.  Perhaps a system where the Confluence page id could be placed in the frontmatter.  True, this would mean I have to create my page in confluence first, but then, rather than specifying the _parents_ page ID once in settings, I could specify each individual page ID in obsidian, and wherever they got moved to in confluence, I could still publish to them.

**Comment by andymac4182** [comment]
Are they all on the same site just in different spaces?

**Comment by jvsteiner** [comment]
yes.  I suppose some people, perhaps freelancers, might have different sites, but I'd guess this is more of an edge case.

**Comment by andymac4182** [comment]
Different spaces in the same site is easy :) Multiple sites will be a bit harder due to needing the different domains but not impossible 👍

**Comment by jvsteiner** [comment]
I realized today that a corollary to this request is that I be able to publish individual pages, as opposed to all pages.  I might be owkring on several, but only be ready to publish one of them right now.

**Comment by andymac4182** [comment]
That is on the cards soon. The next big feature I am looking to build is support for wikilinks which will be a bit of work I think.

**Comment by andymac4182** [comment]
Initial PR for support https://github.com/obsidian-confluence/obsidian-confluence/pull/53 :)

On first publish Obsidian will create the page in Confluence under your normal tree then you can move it if you specify `connie-dont-change-parent-page: true` in the YAML frontmatter.

**Comment by andymac4182** [comment]
Please test in v1.3.0

**Comment by jvsteiner** [comment]
So this was not exactly what I anticipated, but I found that it actually works quite well, and I like it a lot!  

I can create a parent page called "DRAFTS", and my workflow becomes:
1. draft a new page (with `connie-publish: true`);
2. publish it (retrieving the new pageid automatically (nice one!)
3. add the `connie-dont-change-parent-page: true` tag.
4. Move the page wherever in my structure that I need.

What wouldn't work (And I want to be clear that I personally don't need it yet) would be pages in different spaces.  It would be kind of cumbersome to do step (4) between spaces.

A way to mitigate this would be to be able to specify a per-page parent-id in the frontmatter, say, `connie-parent-page-id` rather than have a global parent page id setting.

**Comment by andymac4182** [comment]
That would be possible now. There is a feature called folder note that I haven't documented yet. If you have a note at the root of a folder with the same exact name as the folder it will become the parent page for everything under that folder. You could set the folder note to the page id in the other space. I think I just need to make one tweak to make this work where when it doesn't update the page parent id it also leaves the space alone. It should be a one line change. Will try to get to tonight.

**Comment by andymac4182** [comment]
Sorry just confirmed. It only uses the space when it creates the page. Once the page is created it won't move it between spaces. So you can use Folder Note feature now to set up a folder per space and any notes created in that folder will be created in that space. Will look at adding the manual parent page id feature soon as well.

**Comment by jvsteiner** [comment]
I had a go at implementing one-page-at-a-time publishing, but failed.  Seems the concept of creating the tree from the publishing folder root is deeply embedded.  Not saying it's not possible, just too hard for me to see how to refactor it in an easy way.

**Comment by andymac4182** [comment]
I am slowly pulling the parts required to make single publish a feature as I work through other features. I would guess it will be sometime next week when I am able to release that feature.

**Comment by andymac4182** [comment]
Here is an initial version of single page publish. https://github.com/obsidian-confluence/obsidian-confluence/pull/60 It won't do exactly what you want due to Wikilinks needing a map of all the pages to be published but it will let you update only the open file.
