### ISSUE TITLE
Export as directories/files instead of publishing?

### ISSUE THREAD

**Issue by physixtential** [markdown-confluence/markdown-confluence#397]
I would love to use this, but the confluence I need to publish to is not on the internet so I can't publish directly from my local obsidian client. Do you have any way to export the pages, including images and text formatting to something I can pack into a zip file and then upload to confluence manually?

**Comment by andymac4182** [comment]
Is this for onpremise instance? If so not at the moment. This is on the roadmap to look at and resolve.

**Comment by physixtential** [comment]
> Is this for onpremise instance? If so not at the moment. This is on the roadmap to look at and resolve.

Thanks for the update. I'm not sure exactly what you mean by on-premise. I use obsidian my local machine which does not have access to the confluence directly. The confluence is on a server only accessible through restricted means. I have the ability to transfer raw files there which could then be used to create a page on confluence there. I briefly looked into something like this and I'm actually not even sure if confluence supports such a thing as raw files to pages. I assumed confluence had some sort of flat or binary file format that would translate into an easily uploadable page but I don't know if that's the case.

I can obviously do some copy paste markdown conversion stuff but the major benefit I'm looking for is not having to manually get all the images in the right places again when I have those.

**Comment by andymac4182** [comment]
There is no file format that I am aware of that can include images that will auto upload. You would need to use the CLI of this tool when it support on-premise instances. 

Here is the tracking issue for that https://github.com/markdown-confluence/markdown-confluence/issues/91
