### ISSUE TITLE
Space after link is removed

### ISSUE THREAD

**Issue by matt-smarsh** [markdown-confluence/markdown-confluence#399]
![image](https://github.com/markdown-confluence/markdown-confluence/assets/89040187/cbb9d36c-a393-4137-8431-480ada98877f)
Results in:
![image](https://github.com/markdown-confluence/markdown-confluence/assets/89040187/e0165a6e-2356-455a-90f0-2777e1fb75d3)

Note the trailing space in the output is removed.

**Comment by andymac4182** [comment]
Possible fix for this has been merged  https://github.com/markdown-confluence/markdown-confluence/pull/439
