### ISSUE TITLE
ConfluenceFirstHeadingPageTitle should omit the first heading

### ISSUE THREAD

**Issue by AdamCoulterOz** [markdown-confluence/markdown-confluence#440]
When I set this setting `ConfluenceFirstHeadingPageTitle = true` it correctly makes all the pages use the first heading as the page name, but why wouldn't you then also omit the first page heading in the content then? It essentially makes every page have the same title twice.

**Comment by andymac4182** [comment]
Thanks. Happy to merge the fix :)
