### ISSUE TITLE
Feature Request: Treat README.md as Folder Note

### ISSUE THREAD

**Issue by Deastrom** [markdown-confluence/markdown-confluence#462]
I have played around with this tool a bit and I am currently writing some bash logic to rename README.md files to the same name of their folder to take advantage of the Folder Note feature.

The reasoning behind this is that the README.md for a folder is universally treated as the "folder note" (as implemented in the obsidian plugin).

At the end of the day, having the "Folder note name" being configurable in the CLI would be amaze-balls.

thank you for this project.

**Comment by Deastrom** [comment]
another idea would be to use the connie-title front matter to support folder-notes like functionality.

if connie-title == directory name: do folder-note

**Comment by Deastrom** [comment]
```bash
find confluence-docs -type f -iname "readme.md" | awk -F"/" '{old=$0; sub($NF, $(NF-1), $0); new=$0; system("mv " old " " new ".md")}'
```
The one liner i figured out to do this logic for me

**Comment by andymac4182** [comment]
This should of already been working. I will need to find the bug and fix it. 

Thanks for reporting

**Comment by Deastrom** [comment]
i am running this in 5.4 due to the /app/bridge.js error in latest

```yaml
docker run -u "1000:1000" -it --rm -v "$(pwd):/content" \
  -e ATLASSIAN_API_TOKEN \
  -e ATLASSIAN_USERNAME \
  -e CONFLUENCE_BASE_URL \
  -e CONFLUENCE_PARENT_ID  \
  -e FOLDER_TO_PUBLISH \
  -e CONFLUENCE_CONTENT_ROOT \
  ghcr.io/markdown-confluence/publish:5.4 node /app/index.js
```

**Comment by Deastrom** [comment]
i see it in the changelog now, sorry for the issue, closing this.

**Comment by andymac4182** [comment]
Ahh will get the new update out soon to have that fixed.
