### ISSUE TITLE
Feature: Warn/fail on page changed via Confluence

### ISSUE THREAD

**Issue by eightys3v3n** [markdown-confluence/markdown-confluence#485]
# Currently
If someone changes a Confluence page that was published using Obsidian, it seems the changes are just quietly overwritten on the next Obsidian publish.

# Ideally
If the plugin warned/failed when overwriting changes made in Confluence the user would have the ability to reconcile these changes.

# Why
I work on a team that utilizes Confluence, but I am the only one using Obsidian. If anyone else in the team modifies one of the pages I have published, their edits quietly disappear. If Obsidian warned me about changes on Confluence I could merge changes manually to make using Obsidian safe for more Confluence pages in more places.

# Suggestion of How
The plugin could store the publish date in Obsidian, then compare to the last modification date in Confluence. This would allow alerting or failing to publish when a page was modified on Confluence. The user could bypass this by clicking a button or manually updating/deleting the date in the Obsidian note.

**Comment by andymac4182** [comment]
The plugin checks who the last person editing the page to your user id. If you aren't the last editor it will block the change. 

Here is the code that does the check. https://github.com/markdown-confluence/markdown-confluence/blob/main/packages/lib/src/Publisher.ts#L200-L204

Is it possible you touched the file after the other user so it had your user as the last edited by?

**Comment by eightys3v3n** [comment]
Yes I edited all the test files so I didn't notice that was the case.
Thank you!

**Comment by andymac4182** [comment]
Awesome 👍 

Glad that worked for you 😄
