### ISSUE TITLE
Sync Issues - Confluence Integration - Obsidian Community Plugin

### ISSUE THREAD

**Issue by W1zardsCh3ss** [markdown-confluence/markdown-confluence#500]
Hello,

I'm having an issue publishing the Obsidian folder to Confluence. 

To add some context that may help narrow this down:

- I just recently purchased sync last weekend
- I have sync running on two devices, my desktop (main), and mobile (iOS)
- Both devices are connected to the same remote vault
- I mostly only use the mobile device for reading rather than writing
- I have verified the following:
- Confluence domain
- Atlassian username
- Atlassian API token
- Confluence pare page ID
- Folder to publish
- Additionally, I have excluded the folder that I wanted to publish to Confluence in the Sync settings, hoping this would resolve
- The only error message I receive when I try to initiate the plug is "Syncing already on going"
- When I go to check the confluence page, none of the content is published
- It is important to note that I had this working over the weekend, I'm not sure what changed?
- I cannot recall if I had it working before or after purchasing the native sync from Obsidian
- It's really important to me that I'm able to get this resolved because this was one of the primary movers that influenced me to purchase sync, and to be able to publish my docs to Confluence, that is such a helpful feature.

Please let me know if you need more information from me, and I'm happy to try any suggestions you may have to resolve this.

Sincerely,
Mitchell

**Comment by sigrunixia** [comment]
Adding to this, Obsidian support has been notified already, and I have mostly ruled out Obsidian Sync having a hand in this. However, I'd like to confirm that Obsidian Sync is not having a weird conflict with another publishing service.

**Comment by W1zardsCh3ss** [comment]
Closing this issue.

Resolution: Obsidians native sync settings were the villain in this case. I'll be looking to migrate away from this in the future due to the complexity the user has to undertake and the lack of support from the Obsidian community. I had to learn and solve this issue myself.
