### ISSUE TITLE
changes to obsidian filename to not change Page title in Confluence

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#52]
It seems that whatever the filename is when you first publish, is permanent.  Changing the filename later and republishing does not result in the Page name being changed.

While fixing this, I would suggest introducing a frontmatter setting, perhaps something like `connie-publish-title` to follow your existing convention.  If set,  the filename in Obsidian would not be used at all, and the frontmatter string would be used instead of the filename.  Of course, changing the value of the frontmatter should result in page renaming in Confluence.

**Comment by andymac4182** [comment]
At the moment publish looks up the pages at publish time to find if there is a matching page under the parent page id to update if not then create a new page. 

To allow for page renames you would need to track the page id in the yaml frontmatter after publishing. Would this be acceptable for this to be supported? It would mean all pages published to confluence would have their page id written into the page. 

What would you expect to happen if you had a page id that was deleted and tried to be published again or a page id that didn't exist on that site?

**Comment by jvsteiner** [comment]
> To allow for page renames you would need to track the page id in the yaml frontmatter after publishing.

I certainly think this is a good approach.  Sure, it means you have to publish once, and then copy the ID, but it's a one time operation.  Since I would also like to be able to publish pages individually, and independently of their location in the confluence page structure, this approach would be needed anyway, and meshes nicely.

> What would you expect to happen if you had a page id that was deleted and tried to be published again or a page id that didn't exist on that site?

Throw a helpful error: confluence page id's are "Boss" - Obsidian can learn them, and use them, but cannot assign them.  I don't see another solution.

**Comment by jvsteiner** [comment]
Additionally, I see that I was wrong in my original comment - it does not refuse to change, it - as you said - publishes another child page with the updated title.

**Comment by andymac4182** [comment]
Initial PR for support https://github.com/obsidian-confluence/obsidian-confluence/pull/53 :) 

This will add title support, pageid support and preventing moving files once they are moved.

**Comment by andymac4182** [comment]
Please test in v1.3.0
