### ISSUE TITLE
Feature Request: Add multiple publish folders with unique parent page id's

### ISSUE THREAD

**Issue by b1kjsh** [markdown-confluence/markdown-confluence#538]
I have multiple sections of confluence that I might publish to and it would be go to be able to publish different folders to different parent pages via obsidian.

**Comment by di-org** [comment]
Hear, hear.

**Comment by andymac4182** [comment]
If you use https://markdown-confluence.com/features/folder-note.html with https://markdown-confluence.com/features/yaml-frontmatter.html#connie-dont-change-parent-page you can set up a folder note page that will be a different location and will be the parent for everything below that. 

That use case is part of the reason for that YAML frontmatter option was added 😄

**Comment by b1kjsh** [comment]
Thanks @andymac4182 I think that might just work for me!
