### ISSUE TITLE
Obsidian Confluence Publish Error Page Title is not unique 

### ISSUE THREAD

**Issue by robkisk** [markdown-confluence/markdown-confluence#639]
All of a sudden I can't publish my page to confluence due to the below error even though I have double checked that there are no duplicate names. Tried to reinstall plugin with no success. How can I clear a cache or make this succeed?

<img width="671" alt="image" src="https://github.com/markdown-confluence/markdown-confluence/assets/113189551/ad051e0b-9f2b-4ee0-89a0-bd6e4acc889f">

**Comment by verilykz** [comment]
Hey @robkisk did you find a resolution for this? I'm experiencing a similar issue
