### ISSUE TITLE
Prevent publishing over another users changes

### ISSUE THREAD

**Issue by andymac4182** [markdown-confluence/markdown-confluence#71]
When another user has modified a page published Obsidian then don't allow publish over the top. 

Idea from https://github.com/obsidian-confluence/obsidian-confluence/issues/34

**Comment by andymac4182** [comment]
Resolved in https://github.com/obsidian-confluence/obsidian-confluence/commit/5c42d7787cf4c53098759ac221a81369e033df3d

**Comment by AdamCoulterOz** [comment]
@andymac4182  - this should be optional or overridable. I want to overwrite changes made by other users.

**Comment by andymac4182** [comment]
Will look shortly at adding a setting for this.
