### ISSUE TITLE
Images not getting published

### ISSUE THREAD

**Issue by jvsteiner** [markdown-confluence/markdown-confluence#76]
This was working before, but in the latest version, it seems not to be.  I am not getting any console errors, but the images do not appear.  No further information or clues at this time.

**Comment by jvsteiner** [comment]
Oh, a couple additional things

1. the images in question are transcluded ( using ![[]] syntax) png images.
2. I tried deleting and republishing the entire page.
3. It doesn't matter if I publish a single page or all pages.
4. Publishing brand new pages with transcluded images seems not to work.

It might be a regression :(

**Comment by jvsteiner** [comment]
I found that v1.2.4 was the last version that worked properly in this regard.

**Comment by andymac4182** [comment]
Fix should be in https://github.com/obsidian-confluence/obsidian-confluence/releases/tag/2.0.1 sorry for the regression. Automated tests will be next on the list to help catch these. 

Thanks for testing to find the last working version that made this really fast to find.

**Comment by jvsteiner** [comment]
works now
