### ISSUE TITLE
Not seeing the plugin in "Community Plugins section" 

### ISSUE THREAD

**Issue by kmf** [markdown-confluence/markdown-confluence#88]
Think the readme should mention alternative ways of installation.

**Comment by andymac4182** [comment]
Thanks for the feedback. Will update to include the BRAT steps to install

I have submitted. Waiting to be reviewed https://github.com/obsidianmd/obsidian-releases/pull/1867

**Comment by andymac4182** [comment]
Added to docs https://obsidian-confluence.com/getting-started/installation-brat.html

**Comment by kmf** [comment]
@andymac4182 Thanks for this!

**Comment by andymac4182** [comment]
Launched in the "Community Plugins" :)
